# This file was generated by GoReleaser. DO NOT EDIT.
cask "alc-ng" do
  version "0.2.0"

  on_macos do
    sha256 "65f268d211eff23cd7d089c03fef983bae2fbb0fd5776da78488d28225810f7b"
    url "https://github.com/COMSYS/ALC-NG/releases/download/v#{version}/alc-ng_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "842a350ca2774f2955b7b911999f3f8fed5072cd9c6c611e78dd9013ec2f4300"
      url "https://github.com/COMSYS/ALC-NG/releases/download/v#{version}/alc-ng_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca94252a3ff00c5a63a3e45788f726a1a86be9e8108e464cf23bff2ab93226d5"
      url "https://github.com/COMSYS/ALC-NG/releases/download/v#{version}/alc-ng_#{version}_linux_amd64.tar.gz"
    end
  end

  name "alc-ng"
  desc "Modern LaTeX sanitization tool for arXiv submissions"
  homepage "https://github.com/COMSYS/ALC-NG"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alc-ng"

  # No zap stanza required
end
