name: brew test-bot

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-15-intel, macos-26]

    runs-on: ${{ matrix.os }}

    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        id: setup
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v4
        with:
          path: ${{ steps.setup.outputs.gems-path }}
          key: ${{ matrix.os }}-${{ steps.setup.outputs.gems-hash }}

      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae
